version: '3.8'

volumes:
  static:
  media:

services:
  django-a:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"
        compress: "true"

  django-b:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"
        compress: "true"

  postgres:
    build: ./compose/postgres
    volumes:
      - /data/hacktj_live/postgres:/var/lib/postgresql/data
      - /data/hacktj_live/backups:/backups
    environment:
      - POSTGRES_PASSWORD='817m5da7fyleau^108yko2ib!&+*!0ba38gh%g8ps()56)=gsv'
      - POSTGRES_USER=live_admin
      - POSTGRES_DB=hacktj_live
      - POSTGRES_PORT=5432
    logging:
      driver: "json-file"
      options:
        max-size: "600m"
        max-file: "5"
        compress: "true"

  nginx:
    build: ./compose/nginx
    depends_on:
      # - django-a
      # - django-b
      - postgres
    volumes:
     - static:/data/static
     - media:/data/media
    ports:
     - "1337:80"
    # environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80

  redis:
    build: ./compose/redis
    sysctls:
      net.core.somaxconn: '511'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        compress: "true"
