version: '3.6'

services:
  django:
    build:
      args:
        - DEBUG=false
    ports:
      # - '80:8000'
      - '8000:8000'
    # expose:
    #   - 8000
    volumes:
      - ./static:/app/static
      - ./backups:/app/backup
      - ./logs:/app/logs
    deploy:
      resources:  # for Gunicorn
        # https://github.com/benoitc/gunicorn/issues/1440#issuecomment-411785926
        limits:
          cpus: "0.1"
          memory: "4G"
    environment:
      - DEBUG=false
      - NODE_ENV=production

  postgres:
    volumes:
      - ./data:/var/lib/postgresql/data

  # https-portal:
  #   image: steveltn/https-portal:1.15.0
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   environment:
  #     DOMAINS: 'live.hacktj.org.private -> http://django:8000'
  #     STAGE: 'local'  # {'local', 'staging', 'production'}  # can't use staging or production because TLD has to be public
  #     WEBSOCKET: 'true'
  #     LISTEN_IPV6: 'true'
  #     ERROR_LOG: stdout
  #     ACCESS_LOG: stderr

secrets:
  secret_key:
    file: ./compose/secrets/production/secret_key.txt
  django_superuser_username:
    file: ./compose/secrets/production/django_superuser_username.txt
  django_superuser_password:
    file: ./compose/secrets/production/django_superuser_password.txt
  django_superuser_email:
    file: ./compose/secrets/production/django_superuser_email.txt
  postgres_user:
    file: ./compose/secrets/production/postgres_user.txt
  postgres_password:
    file: ./compose/secrets/production/postgres_password.txt
  postgres_db:
    file: ./compose/secrets/production/postgres_db.txt
  sendgrid_api_key:
    file: ./compose/secrets/production/sendgrid_api_key.txt
