version: '3.8'

volumes:
  static:
  backups:

services:
  django:
    expose:
      - 8000
    volumes:
      - static:/app/static
      - backups:/app/backup
    deploy:
      resources:  # for Gunicorn
        # https://github.com/benoitc/gunicorn/issues/1440#issuecomment-411785926
        limits:
          cpus: "0.1"
          memory: "4G"
    env_file:
      - .env
    environment:
      - DEBUG=false
      - NODE_ENV=production

  postgres:
    env_file:
      - .env

  nginx:
    build: ./compose/nginx
    restart: always
    ports:
      - "1379:80"
    depends_on:
      - django
    volumes:
      - static:/usr/share/nginx/html/static/
