version: '3.8'

volumes:
  postgres_data_dev:
  postgres_backup_dev:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  postgres:
    build: ./compose/postgres
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file:
      - .env.local

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'
