version: '3.8'

volumes:
  postgres_data_dev:
  postgres_backup_dev:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
      POSTGRES_USER: live_admin
      POSTGRES_DB: hacktj_live
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
      POSTGRES_USER: live_admin
      POSTGRES_DB: hacktj_live

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'
