version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    sysctls:
      net.core.somaxconn: 2048
    command: /start.sh
    depends_on:
      - postgres
      - redis
      - memcached

  postgres:
    build: ./compose/postgres
    restart: always
    shm_size: 256MB

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  memcached:
    build: ./compose/memcached
    restart: always
