version: '3.6'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      # args:
      #   - DEBUG=${DEBUG}
    restart: always
    sysctls:
      net.core.somaxconn: 2048
    command: ./compose/django/start.sh
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - DOCKER=true
    depends_on:
      - postgres
      - redis
      - memcached
    volumes:
      - ./judge/fixtures:/app/judge/fixtures

  postgres:
    image: postgres:13.5-alpine3.14
    restart: always
    shm_size: 256MB
    environment:
      # - PGHOST=postgres
      - PGPORT=${POSTGRES_PORT:-5432}
      # - PGDATABASE=${POSTGRES_DB}
      # - PGUSER=${POSTGRES_USER}
      # - PGPASSWORD=${POSTGRES_PASSWORD}
      # - PGOPTIONS=${POSTGRES_INITDB_ARGS}

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  memcached:
    image: memcached:1.6.12-alpine3.14
    restart: always
