version: '3.6'

services:
  django:
    build:
      args:
        - DEBUG=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - NODE_ENV=development

secrets:
  secret_key:
    file: ./compose/secrets/debug/secret_key.txt
  django_superuser_username:
    file: ./compose/secrets/debug/django_superuser_username.txt
  django_superuser_password:
    file: ./compose/secrets/debug/django_superuser_password.txt
  django_superuser_email:
    file: ./compose/secrets/debug/django_superuser_email.txt
  postgres_user:
    file: ./compose/secrets/debug/postgres_user.txt
  postgres_password:
    file: ./compose/secrets/debug/postgres_password.txt
  postgres_db:
    file: ./compose/secrets/debug/postgres_db.txt
  sendgrid_api_key:
    file: ./compose/secrets/debug/sendgrid_api_key.txt
