version: '3.6'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      # args:
      #   - DEBUG=${DEBUG}
    restart: always
    sysctls:
      net.core.somaxconn: 2048
    command: ./compose/django/start.sh
    environment:
      - SECRET_KEY=/run/secrets/secret_key
      - DJANGO_SUPERUSER_USERNAME=/run/secrets/django_superuser_username
      - DJANGO_SUPERUSER_PASSWORD=/run/secrets/django_superuser_password
      - DJANGO_SUPERUSER_EMAIL=/run/secrets/django_superuser_email
      - POSTGRES_USER=/run/secrets/postgres_user
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
      - POSTGRES_PORT=5432
      - POSTGRES_DB=/run/secrets/postgres_db
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - SENDGRID_API_KEY=/run/secrets/sendgrid_api_key
      - DOCKER=true
      # - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256 --data-checksums
      # - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    depends_on:
      - postgres
      - redis
      - memcached
    volumes:
      - ./utils/fixtures:/app/utils/fixtures
      - ./judge/fixtures:/app/judge/fixtures
    secrets:
      - secret_key
      - django_superuser_username
      - django_superuser_password
      - django_superuser_email
      - postgres_user
      - postgres_password
      - postgres_db
      - sendgrid_api_key

  postgres:
    image: postgres:13.2-alpine
    restart: always
    shm_size: 256MB
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_PORT=5432
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - PGPORT=${POSTGRES_PORT:-5432}
      # - PGHOST=postgres
      # - PGDATABASE=${POSTGRES_DB}
      # - PGUSER=${POSTGRES_USER}
      # - PGPASSWORD=${POSTGRES_PASSWORD}
      # - PGOPTIONS=${POSTGRES_INITDB_ARGS}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256 --data-checksums
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  memcached:
    image: memcached:1.6.9-alpine
    restart: always

secrets:
  # just to keep `docker-compose` from complaining about
  # `Service "postgres" uses an undefined secret`
  secret_key:
    external: true
  django_superuser_username:
    external: true
  django_superuser_password:
    external: true
  django_superuser_email:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true
  sendgrid_api_key:
    external: true
