version: '3.8'

volumes:
  postgres_data_dev:
  postgres_backup_dev:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    sysctls:
      net.core.somaxconn: 2048
    command: /start.sh
    depends_on:
      - postgres
      - redis
      - memcached

  postgres:
    build: ./compose/postgres
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    shm_size: 256MB

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  memcached:
    build: ./compose/memcached
    restart: always
