version: '3.6'

services:
  django:
    build:
      args:
        - DEBUG=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - DEBUG=true
      - NODE_ENV=development

  postgres:
    env_file:
      - .env.local

  redis:
    build: ./compose/redis
    restart: always
    sysctls:
      net.core.somaxconn: '511'
