#!/usr/bin/env bash
if [ "$1" == "dev" ]; then
  docker compose --env-file .env.local -f docker-compose.yml -f docker-compose.dev.yml up --force-recreate --build
elif [ "$1" == "prod" ]; then
  docker compose --env-file .env -f docker-compose.yml -f docker-compose.prod.yml up --force-recreate --build
else
  echo "Invalid argument"
  exit 1
fi
