# Generated by Django 3.0.8 on 2020-08-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('mean', models.DecimalField(decimal_places=8, default=0.0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=8, default=1.0, max_digits=12)),
                ('numberOfVotes', models.IntegerField()),
                ('timesSeen', models.IntegerField()),
                ('timesSkipped', models.IntegerField()),
                ('prioritize', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
