# Generated by Django 3.1.6 on 2021-02-26 18:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.liveuser')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alpha', models.DecimalField(decimal_places=8, default=10, max_digits=12)),
                ('beta', models.DecimalField(decimal_places=8, default=1, max_digits=12)),
                ('read_welcome', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('link', models.URLField(blank=True)),
                ('means', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12), size=4)),
                ('variances', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12), size=4)),
                ('numberOfVotes', models.IntegerField(default=0)),
                ('timesSeen', models.IntegerField(default=0)),
                ('timesSkipped', models.IntegerField(default=0)),
                ('prioritize', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.annotator')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_loser', to='judge.project')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_winner', to='judge.project')),
            ],
        ),
        migrations.AddField(
            model_name='annotator',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_current', to='judge.project'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='ignore',
            field=models.ManyToManyField(related_name='annotator_ignore', to='judge.Project'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_prev', to='judge.project'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='viewed',
            field=models.ManyToManyField(related_name='annotator_viewed', to='judge.Project'),
        ),
    ]
