# Generated by Django 3.1.6 on 2021-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='means',
        ),
        migrations.RemoveField(
            model_name='project',
            name='variances',
        ),
        migrations.AddField(
            model_name='project',
            name='complexityMean',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='complexityVariance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='designMean',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='designVariance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='functionalityMean',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='functionalityVariance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='innovationMean',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='innovationVariance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='overallMean',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='overallVariance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
    ]
