# Generated by Django 3.1.6 on 2021-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="means",
        ),
        migrations.RemoveField(
            model_name="project",
            name="variances",
        ),
        migrations.AddField(
            model_name="project",
            name="complexity_mean",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="complexity_variance",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="design_mean",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="design_variance",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="functionality_mean",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="functionality_variance",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="innovation_mean",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="innovation_variance",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="overall_mean",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="overall_variance",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
    ]
