# Generated by Django 3.0.8 on 2020-09-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0002_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='judge',
        ),
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.DecimalField(decimal_places=8, default=10, max_digits=12)),
                ('beta', models.DecimalField(decimal_places=8, default=1, max_digits=12)),
                ('read_welcome', models.BooleanField(default=False)),
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_next', to='judge.Project')),
                ('prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_prev', to='judge.Project')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='annotator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='judge.Annotator'),
            preserve_default=False,
        ),
    ]
