# Generated by Django 3.1.6 on 2021-03-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0002_auto_20210331_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="complexity_variance",
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="project",
            name="design_variance",
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="project",
            name="functionality_variance",
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="project",
            name="innovation_variance",
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="project",
            name="overall_variance",
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12),
        ),
    ]
