# Generated by Django 3.0.8 on 2020-09-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20200903_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='ignore',
            field=models.ManyToManyField(related_name='annotator_ignore', to='judge.Project'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_next', to='judge.Project'),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_prev', to='judge.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='numberOfVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='timesSeen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='timesSkipped',
            field=models.IntegerField(default=0),
        ),
    ]
