# Generated by Django 3.1.6 on 2021-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0003_auto_20210331_1933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="criterion",
            field=models.CharField(
                choices=[
                    ("overall", "Overall"),
                    ("innovation", "Innovation"),
                    ("functionality", "Functionality"),
                    ("design", "Design"),
                    ("complexity", "Technical Complexity"),
                ],
                default=0,
                max_length=255,
            ),
        ),
    ]
