# Generated by Django 3.1.3 on 2020-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20200918_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
