# Generated by Django 3.1.7 on 2021-04-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0004_auto_20210331_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="criterion",
            field=models.CharField(
                choices=[
                    ("overall", "Overall"),
                    ("innovation", "Innovation"),
                    ("functionality", "Functionality"),
                    ("design", "Design"),
                    ("complexity", "Technical Complexity"),
                ],
                default="overall",
                max_length=13,
            ),
        ),
    ]
