# Generated by Django 3.2.9 on 2021-11-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0005_auto_20210405_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
