# Generated by Django 3.1.3 on 2020-11-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20201119_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='viewed',
            field=models.ManyToManyField(related_name='annotator_viewed', to='judge.Project'),
        ),
    ]
