# Generated by Django 3.1.3 on 2020-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_annotator_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
