# Generated by Django 4.0 on 2021-12-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0006_auto_20211114_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotator",
            name="current",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_current",
                to="judge.project",
            ),
        ),
        migrations.AlterField(
            model_name="annotator",
            name="ignore",
            field=models.ManyToManyField(
                related_name="%(class)s_ignore", to="judge.Project"
            ),
        ),
        migrations.AlterField(
            model_name="annotator",
            name="prev",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_prev",
                to="judge.project",
            ),
        ),
        migrations.AlterField(
            model_name="annotator",
            name="viewed",
            field=models.ManyToManyField(
                related_name="%(class)s_viewed", to="judge.Project"
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="loser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_loser",
                to="judge.project",
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_winner",
                to="judge.project",
            ),
        ),
    ]
