# Generated by Django 4.0 on 2021-12-18 19:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("judge", "0007_alter_annotator_current_alter_annotator_ignore_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
