# Generated by Django 3.1.3 on 2020-11-29 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0008_auto_20201129_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='judge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotator', to=settings.AUTH_USER_MODEL),
        ),
    ]
