# Generated by Django 3.1.3 on 2020-11-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20201129_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='current',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_current', to='judge.project'),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='prev',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_prev', to='judge.project'),
        ),
    ]
