# Generated by Django 3.1.4 on 2020-12-06 02:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20201129_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='project',
            name='variance',
        ),
        migrations.AddField(
            model_name='decision',
            name='criterion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='means',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12), default=list, size=4),
        ),
        migrations.AddField(
            model_name='project',
            name='variances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12), default=list, size=4),
        ),
    ]
