# Generated by Django 3.1.4 on 2020-12-06 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20201206_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='means',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12), size=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='variances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=1.0, max_digits=12), size=4),
        ),
    ]
