# Generated by Django 3.1.4 on 2020-12-06 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0013_auto_20201206_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
