# Generated by Django 3.1.4 on 2020-12-13 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_current', to='judge.project'),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_prev', to='judge.project'),
        ),
    ]
