name: Gixy CI

on:
  push:
    # paths: ./compose/nginx/nginx.conf
  pull_request:
    # paths: ./compose/nginx/nginx.conf

jobs:
  gixy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # Installs Gixy
      - name: Install Gixy
        run: python3 -m pip install gixy

      # Run Gixy
      - name: Run Gixy
        run: gixy ./compose/nginx/nginx.conf
