name: Gixy CI

on:
  push:
    paths:
    - './compose/nginx/nginx.conf'
  pull_request:
    paths:
    - './compose/nginx/nginx.conf'

jobs:
  gixy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Gixy
        run: |
          python3 -m pip install setuptools
          python3 -m pip install gixy

      - name: Run Gixy
        run: gixy ./compose/nginx/nginx.conf
