name: Gixy CI

on:
  push:
    # paths: ./compose/nginx/nginx.conf
  pull_request:
    # paths: ./compose/nginx/nginx.conf

jobs:
  gixy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: Install and run Gixy
        run: |
          python3 -m pip install setuptools
          python3 -m pip install gixy
          gixy ./compose/nginx/nginx.conf
