name: Hadolint CI

on:
  push:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Django Dockerfile
        uses: brpaz/hadolint-action
        with:
          dockerfile: "./compose/django/Dockerfile"
      - name: Lint Nginx Dockerfile
        uses: brpaz/hadolint-action
        with:
          dockerfile: "./compose/nginx/Dockerfile"
      - name: Lint Postgres Dockerfile
        uses: brpaz/hadolint-action
        with:
          dockerfile: "./compose/postgres/Dockerfile"
      - name: Lint Redis Dockerfile
        uses: brpaz/hadolint-action
        with:
          dockerfile: "./compose/redis/Dockerfile"
