name: Lighthouse CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.1
          lhci autorun
