name: PyCharm Python Security Scanner

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PyCharm Python Security Scanner
      uses: tonybaloney/pycharm-security@1.22.2
