name: ShellCheck

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        run: |
          for f in $(find . -type f \( -name '*.sh' \)); do
            echo $f
            shellcheck $f
          done
